/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop;

/**
 *
 * @author omer
 */
public class WindowApp extends javax.swing.JFrame {

    private static WindowApp instance;

    public static WindowApp getInstance()
    {
        if (instance == null)
            instance = new WindowApp();

        return instance;
    }

    /**
     * Creates new form WindowApp
     */
    private WindowApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        friendTable = new javax.swing.JTable();
        addFriendButton = new javax.swing.JButton();
        removeFriendButton = new javax.swing.JButton();
        createChatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        friendTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(friendTable);

        addFriendButton.setText("Arkadaş Ekle");

        removeFriendButton.setText("Arkadaşı Sil");

        createChatButton.setText("Sohbet Başlat");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(addFriendButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(removeFriendButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(createChatButton)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addFriendButton)
                    .add(removeFriendButton)
                    .add(createChatButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriendButton;
    private javax.swing.JButton createChatButton;
    private javax.swing.JTable friendTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeFriendButton;
    // End of variables declaration//GEN-END:variables
}
